### ISSUE TITLE
cluster fails when DNS hostnames not enabled

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-aws-cloudformation#10]
## Description
When using the cluster configuration it attempts to resolve the DNS name.  If the VPC does not have DNS hostnames enabled this will fail.

```
2017-02-13T15:40:23.845Z verbose: tryUntil: getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443 tries left:
2017-02-13T15:40:23.846Z debug:  {"message":"getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443","stack":"Error: getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443\n    at errnoException (dns.js:26:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"ip-10-1-1-230.ec2.internal","host":"ip-10-1-1-230.ec2.internal","port":443}
2017-02-13T15:40:23.847Z verbose: Max tries reached.
2017-02-13T15:40:23.847Z verbose: tryUntil: getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443 tries left:
2017-02-13T15:40:23.847Z debug:  {"message":"getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443","stack":"Error: getaddrinfo ENOTFOUND ip-10-1-1-230.ec2.internal ip-10-1-1-230.ec2.internal:443\n    at errnoException (dns.js:26:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"ip-10-1-1-230.ec2.internal","host":"ip-10-1-1-230.ec2.internal","port":443}
```

```
aws ec2 describe-vpc-attribute --vpc-id "vpc-12d52674" --attribute enableDnsHostnames

{
    "VpcId": "vpc-12d52674",
    "EnableDnsHostnames": {
        "Value": false
    }
}
```

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 4

**Comment by crosbygw** [comment]
Enabling DNS hostname on VPC is no longer required for HA templates.
Resolved in v2.6.0: https://github.com/F5Networks/f5-aws-cloudformation/tree/v2.6.0
