### ISSUE TITLE
/tm/sys/available returning 503 errors

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-aws-cloudformation#146]
## Description
During deployment one of the hosts required restarting restjavad for the process to complete

```
2021-02-12T11:30:05.518Z silly: [pid: 16769] [lib/util.js] tryUntil: got error {"message":"Unable to process request /tm/sys/available. Service is unavailable.","stack":"Error: Unable to process request /tm/sys/available. Service is unavailable.\n    at IControl.parseError (/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/lib/iControl.js:339:21)\n    at IncomingMessage.response.on (/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/lib/iControl.js:304:46)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","code":503}
2021-02-12T11:30:05.518Z verbose: [pid: 16769] [lib/util.js] tryUntil error: Unable to process request /tm/sys/available. Service is unavailable. tries left: 0
2021-02-12T11:30:05.518Z silly: [pid: 16769] [lib/util.js] tryUntil: retryOrReject: numRemaining: 0 , code: 503 , message: Unable to process request /tm/sys/available. Service is unavailable.
2021-02-12T11:30:05.519Z silly: [pid: 16769] [lib/util.js] tryUntil: got error {"code":503,"message":"tryUntil: max tries reached: Unable to process request /tm/sys/available. Service is unavailable.","name":"Error"}
2021-02-12T11:30:05.519Z verbose: [pid: 16769] [lib/util.js] tryUntil error: tryUntil: max tries reached: Unable to process request /tm/sys/available. Service is unavailable. tries left: 70
2021-02-12T11:30:05.519Z silly: [pid: 16769] [lib/util.js] tryUntil: retryOrReject: numRemaining: 70 , code: 503 , message: tryUntil: max tries reached: Unable to process request /tm/sys/available. Service is unavailable.
2021-02-12T11:30:15.519Z debug: [pid: 16769] [lib/bigIp.js] list localhost /shared/echo/available
```

## Template
For bugs, enter the template with which you are experiencing issues below.
https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation/master/supported/failover/same-net/via-api/3nic/existing-stack/payg/f5-existing-stack-same-az-cluster-payg-3nic-bigip.template

Version 5.11.0

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by shyawnkarim** [comment]
I just deployed this template and didn't have any issues. It's possible this was an intermittent race condition or other rare occurrence. If this issue continues for you, can you supply the parameters you used, region, and instance type?

**Comment by chen23** [comment]
It is intermittent (I have not seen it again after 3 more deploys), but if there's code to catch the condition and restart restjavad after X failures it could be helpful. Thanks!

**Comment by shyawnkarim** [comment]
Do you still have the logs? I'd like to know where in the process it stopped.

**Comment by chen23** [comment]
unfortunately i ended up deleting that stack.  once i restarted restjavad the process went through to completion.

**Comment by chen23** [comment]
ran into another failure (after deploying about 4 times w/out issues).
```
2021-02-15T04:21:10.034Z silly: [pid: 16803] [lib/util.js] tryUntil: got error {"message":"Unable to process request /tm/sys/available. Service is unavailable.","stack":"Error: Unable to process request
 /tm/sys/available. Service is unavailable.\n    at IControl.parseError (/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/lib/iControl.js:339:21)\n    at IncomingMessage.response.on (/config/c
loud/aws/node_modules/@f5devcentral/f5-cloud-libs/lib/iControl.js:304:46)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:10
64:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","code":503}
2021-02-15T04:21:10.034Z silly: [pid: 16803] [lib/util.js] typeof err object
2021-02-15T04:21:10.034Z verbose: [pid: 16803] [lib/util.js] tryUntil error: Unable to process request /tm/sys/available. Service is unavailable. tries left: 0
2021-02-15T04:21:10.034Z silly: [pid: 16803] [lib/util.js] tryUntil: retryOrReject: numRemaining: 0 , code: 503 , message: Unable to process request /tm/sys/available. Service is unavailable.
2021-02-15T04:21:10.034Z verbose: [pid: 16803] [lib/util.js] Max tries reached.
2021-02-15T04:21:10.035Z silly: [pid: 16803] [lib/util.js] tryUntil: got error {"code":503,"message":"tryUntil: max tries reached: Unable to process request /tm/sys/available. Service is unavailable.","
name":"Error"}
2021-02-15T04:21:10.035Z silly: [pid: 16803] [lib/util.js] typeof err object
2021-02-15T04:21:10.035Z verbose: [pid: 16803] [lib/util.js] tryUntil error: tryUntil: max tries reached: Unable to process request /tm/sys/available. Service is unavailable. tries left: 3
2021-02-15T04:21:10.035Z silly: [pid: 16803] [lib/util.js] tryUntil: retryOrReject: numRemaining: 3 , code: 503 , message: tryUntil: max tries reached: Unable to process request /tm/sys/available. Servi
ce is unavailable.
```
[failed-install.log](https://github.com/F5Networks/f5-aws-cloudformation/files/5979490/failed-install.log)

**Comment by shyawnkarim** [comment]
Thanks for sending that over. I made a mistake and should have asked for a qkview. Do you still happen to that?

**Comment by shyawnkarim** [comment]
Closing. Please reopen if you continue to run into this.
