### ISSUE TITLE
failure to run 3-nic standalone

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-aws-cloudformation#152]
## Do you already have an issue opened with F5 support?

No

## Description

Error when running 3-nic standalone BYOL template 5.11

```
2021-05-07 01:11:41,138 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2021-05-07 01:11:41,138 - util.py[DEBUG]: Writing to /opt/cloud/instances/i-0900102adf6aed2df/sem/config_scripts_user - wb: [644] 20 bytes
2021-05-07 01:11:41,138 - util.py[DEBUG]: Restoring selinux mode for /opt/cloud/instances/i-0900102adf6aed2df/sem/config_scripts_user (recursive=False)
2021-05-07 01:11:41,138 - util.py[DEBUG]: Restoring selinux mode for /opt/cloud/instances/i-0900102adf6aed2df/sem/config_scripts_user (recursive=False)
2021-05-07 01:11:41,139 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/opt/cloud/instances/i-0900102adf6aed2df/sem/config_scripts
_user'>)
2021-05-07 01:11:41,139 - util.py[DEBUG]: Running command ['/opt/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=False, capture=False)
2021-05-07 01:16:56,997 - util.py[WARNING]: Failed running /opt/cloud/instance/scripts/part-001 [1]
2021-05-07 01:16:56,997 - util.py[DEBUG]: Failed running /opt/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 876, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2068, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/opt/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
```
## Template
For bugs, enter the template with which you are experiencing issues below.

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by chen23** [comment]
```
[admin@ip-10-1-1-213:NO LICENSE:Standalone] ~ # cat /var/log/cfn-init.log
2021-05-06 18:11:42,144 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2021-05-06 18:11:42,144 [DEBUG] Describing resource Bigip1Instance in stack arn:aws:cloudformation:us-east-1:xxxx:stack/erchen/81662e00-aed0-11eb-be0e-12146b70620f
2021-05-06 18:12:42,145 [WARNING] Timeout of 60 seconds breached
2021-05-06 18:12:42,146 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError
2021-05-06 18:12:42,150 [DEBUG] Sleeping for 0.992639 seconds before retrying
2021-05-06 18:12:43,146 [DEBUG] Describing resource Bigip1Instance in stack arn:aws:cloudformation:us-east-1:xxxx:stack/erchen/81662e00-aed0-11eb-be0e-12146b70620f
2021-05-06 18:13:43,146 [WARNING] Timeout of 60 seconds breached
2021-05-06 18:13:43,148 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError
2021-05-06 18:13:43,149 [DEBUG] Sleeping for 2.631358 seconds before retrying
2021-05-06 18:13:45,783 [DEBUG] Describing resource Bigip1Instance in stack arn:aws:cloudformation:us-east-1:xxx:stack/erchen/81662e00-aed0-11eb-be0e-12146b70620f
2021-05-06 18:14:45,784 [WARNING] Timeout of 60 seconds breached
2021-05-06 18:14:45,784 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError
2021-05-06 18:14:45,785 [DEBUG] Sleeping for 5.982357 seconds before retrying
2021-05-06 18:14:51,773 [DEBUG] Describing resource Bigip1Instance in stack arn:aws:cloudformation:us-east-1:xxxx:stack/erchen/81662e00-aed0-11eb-be0e-12146b70620f
2021-05-06 18:15:51,773 [WARNING] Timeout of 60 seconds breached
2021-05-06 18:15:51,774 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError
2021-05-06 18:15:51,775 [DEBUG] Sleeping for 5.201285 seconds before retrying
2021-05-06 18:15:56,978 [DEBUG] Describing resource Bigip1Instance in stack arn:aws:cloudformation:us-east-1:xxxxx:stack/erchen/81662e00-aed0-11eb-be0e-12146b70620f
2021-05-06 18:16:56,978 [WARNING] Timeout of 60 seconds breached
2021-05-06 18:16:56,979 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 231, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError
```

**Comment by shyawnkarim** [comment]
Since this is a sev1, has there been an SR opened?

**Comment by chen23** [comment]
> Since this is a sev1, has there been an SR opened?

I changed the severity. Same issue. But using a different template now that does not have the issue.

**Comment by shyawnkarim** [comment]
I just successfully deployed this template. Can I get the parameters you used?

**Comment by chen23** [comment]
found the root cause.  the VPC was missing a route to the IGW.
