### ISSUE TITLE
Restore from S3 backup UCS file fails

### ISSUE THREAD

**Issue by panama63119** [F5Networks/f5-aws-cloudformation#55]
Restore from backup fails to execute:

Restore from backup UCS is still failing:

2018-09-21T16:29:20.630Z debug: [pid: 27906] [lib/bigIp.js]  {"kind":"tm:sys:mcp-state:mcp-statestats","selfLink":"https://localhost/mgmt/tm/sys/mcp-state?ver=13.1.1","entries":{"https://localhost/mgmt/tm/s
ys/mcp-state/0":{"nestedStats":{"entries":{"endPlatformIdReceived":{"description":"true"},"lastLoad":{"description":"high-config-load-succeed"},"phase":{"description":"running"}}}}}}
2018-09-21T16:29:21.471Z warn: [pid: 27906] [scripts/autoscale.js] /config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/scripts/updateAutoScaleUcs failed: Error: Command failed: /config/cloud/aws/node
_modules/@f5devcentral/f5-cloud-libs/scripts/updateAutoScaleUcs --original-ucs /config/ucsOriginal_1537547346673.ucs --updated-ucs /config/ucsUpdated_1537547346673.ucs --cloud-provider aws --extract-directo
ry /config/cloud/ucsRestore
Traceback (most recent call last):
  File "/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/scripts/updateAutoScaleUcs", line 263, in <module>
    main()
  File "/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/scripts/updateAutoScaleUcs", line 243, in main
    removeFiles(extract_ucs_dir + '/config/cloud/keys', 'cloudLocal*')
  File "/config/cloud/aws/node_modules/@f5devcentral/f5-cloud-libs/scripts/updateAutoScaleUcs", line 127, in removeFiles
    for f in os.listdir(dir):
OSError: [Errno 2] No such file or directory: '/config/cloud/ucsRestore/config/cloud/keys'

**Comment by kskoh** [comment]
@panama63119 Are you using the latest LTM or WAF autoscale templates from the master branch.  Please provide links for my reference?  Are they PAYG or BYOL? This issue if reproducible I would think that both autoscale templates will be affected.  Let me know.

**Comment by panama63119** [comment]
I am using the WAF template and PAYG. This is the template I used:

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/payg

Thomas Heljula
Sr. IT Engineer

W: 314.770.3482  |  www.lumeris.com<http://www.lumeris.com/>
13900 Riverport Dr., St. Louis, MO 63043 | (Map<https://www.google.com/maps/place/13900+Riverport+Dr,+Maryland+Heights,+MO+63043/@38.7545321,-90.4721761,17z/data=!3m1!4b1!4m5!3m4!1s0x87df2e6adc27893b:0x189b6b6df0000a18!8m2!3d38.7545321!4d-90.4699874>)

[BestInKlassLogo]

Best in KLAS • Three years running.

**Comment by kskoh** [comment]
Yes, I reproduced the issue.  Researching further and will get back with some updates this week.  Thanks.

**Comment by shyawnkarim** [comment]
Closing. There have been several releases that update and address bugs with the UCS backup.
